#!/bin/bash
# HUDの御霊顔アイコン src/faces.js を、公式配布の顔アイコン(透過)から生成する。
# 出どころ: kitan-lore MCP get_spirit の sheets「顔アイコン(透過)」(1024x1024 webp)。
# HUDでは38px(dpr2で76px)表示なので96pxに縮めてPNG(透過維持)でdata URI化する。
set -euo pipefail
cd "$(dirname "$0")/.."
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

IDS=(anne oto nemu nekomata benten uka izuna shion sakuya shiori)
OUT=src/faces.js
{
  echo "// generated by scripts/build-faces.sh — do not edit"
  echo "// 公式配布の顔アイコン(透過)を96pxに縮小したもの"
  echo "// https://vibe.co.jp/luna-occulta/media/img/canon/<id>_icon.webp"
  echo "const FACE_DATA = {"
  for id in "${IDS[@]}"; do
    curl -sf "https://vibe.co.jp/luna-occulta/media/img/canon/${id}_icon.webp" -o "$TMP/$id.webp"
    ffmpeg -y -loglevel error -i "$TMP/$id.webp" -vf scale=96:96 "$TMP/$id.png"
    echo "  $id: \"data:image/png;base64,$(base64 -i "$TMP/$id.png")\","
  done
  echo "};"
} > "$OUT"
echo "$OUT: $(stat -f%z "$OUT") bytes (${#IDS[@]} icons)"
